### ISSUE TITLE
Test failure with ruby-progressbar 1.0.1

### ISSUE THREAD

**Issue by graaff** [jfelchner/ruby-progressbar#21]
Using ruby 1.8.7 (2012-06-29 patchlevel 370) [x86_64-linux] I'm getting the following two test failures with ruby-progressbar 1.0.1:

```
Failures:

  1) ProgressBar::Time#now when Time is being mocked by Timecop retrieves the unmocked Timecop time
     Failure/Error: subject { ProgressBar::Time.now ::TimeMockedWithTimecop }
       (<TimeMockedWithTimecop (class)>).now(no args)
           expected: 0 times
           received: 1 time
     # ./lib/progress_bar/time.rb:6:in `send'
     # ./lib/progress_bar/time.rb:6:in `old_now'
     # ./spec/../spec/support/timecop.rb:16:in `now'
     # ./spec/progress_bar/time_spec.rb:20
     # ./spec/progress_bar/time_spec.rb:26

  2) ProgressBar::Time#now when Time is being mocked by Delorean retrieves the unmocked Delorean time
     Failure/Error: subject { ProgressBar::Time.now ::TimeMockedWithDelorean }
       (<TimeMockedWithDelorean (class)>).now(no args)
           expected: 0 times
           received: 1 time
     # ./lib/progress_bar/time.rb:6:in `send'
     # ./lib/progress_bar/time.rb:6:in `old_now'
     # ./spec/../spec/support/timecop.rb:16:in `now'
     # ./spec/progress_bar/time_spec.rb:31
     # ./spec/progress_bar/time_spec.rb:37

Finished in 0.82176 seconds
102 examples, 2 failures
```
